version: '3'
services:
  traefik:
    image: traefik:latest # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Tr√¶fik to listen to docker
    ports:
      - '80:80' # The HTTP port
      - '8080:8080' # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  service1:
    build: .
    environment:
      - MY_MESSAGE=load1
    labels:
      - 'traefik.frontend.rule=Host:127.0.0.1'
      - 'traefik.backend=load'
      
  service2:
    build: .
    environment:
      - MY_MESSAGE=load2
    labels:
      - 'traefik.frontend.rule=Host:127.0.0.1'
      - 'traefik.backend=load'    
